export const RETRIEVE_RATES = 'RETRIEVE_RATES';
export const RECEIVE_RESULT_RATES = 'RECEIVE_RESULT_RATES';
export const DO_CONVERSION = 'DO_CONVERSION';
export const CHANGE_AMOUNT = 'CHANGE_AMOUNT';
export const CHANGE_TARGET = 'CHANGE_TARGET';
export const UPDATE_CURRENT_RATE = 'UPDATE_CURRENT_RATE';



